/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/control-plane/wrangler.d1.jsonc --env=preview --include-runtime=false apps/control-plane/worker-configuration.d.ts` (hash: c7ce49387a7add1394d315d1ed2dcc3b)
interface __BaseEnv_Env {
	CONTROL_DB_FRESH: D1Database;
	ORCHESTRATOR: Fetcher /* openbot-orchestrator-preview */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./entry.d1");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
