/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/capability-gateway/wrangler.d1.jsonc --env=preview --include-runtime=false apps/capability-gateway/worker-configuration.d.ts` (hash: 4d3616ea4fd01b8fef6809c6754da959)
interface __BaseEnv_Env {
	CONTROL_DB_FRESH: D1Database;
	SANDBOX_EXECUTION: Service /* entrypoint SandboxExecutionService from openbot-sandbox-runner-preview */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entry.d1");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
