/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/capability-gateway/wrangler.d1.jsonc --env=preview --include-runtime=false apps/capability-gateway/worker-configuration.d.ts` (hash: c792479d9a5a7c410b799ebdf934a546)
interface __BaseEnv_Env {
	CONTROL_DB_FRESH: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./entry.d1");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
