import { z } from "zod";

export const DENY_CODES_V1 = [
    "account_not_active",
    "access_request_pending",
    "action_approval_required",
    "artifact_snapshot_pending",
    "bot_busy",
    "bot_not_active",
    "bot_profile_changed",
    "bot_revision_changed",
    "catalog_dependency_changed",
    "catalog_dependency_disabled",
    "cleanup_blocked",
    "code_execution_not_enabled",
    "code_execution_unverified",
    "code_language_not_allowed",
    "compute_authority_wrong_grant_type",
    "compute_authority_denied",
    "compute_dependency_changed",
    "compute_grant_dependency_changed",
    "confirmation_consumed",
    "confirmation_exists",
    "confirmation_session_mismatch",
    "confirmation_stale",
    "connection_required",
    "connector_schema_changed",
    "connector_review_changed",
    "cross_authorization_policy",
    "cross_deployment_policy",
    "data_class_unknown",
    "destination_not_allowed",
    "destructive_permission_denied",
    "grant_not_active",
    "gateway_sequence_denied",
    "idempotency_mismatch",
    "impact_changed",
    "jurisdiction_unverified",
    "limit_exceeded",
    "model_route_unavailable",
    "outbound_field_not_allowed",
    "permission_not_selected",
    "provider_activity_forbidden",
    "resource_scope_unsupported",
    "run_attempt_stale",
    "role_denied",
    "sandbox_cleanup_changed",
    "sandbox_data_profile_denied",
    "sandbox_dispatch_denied",
    "sandbox_dispatch_replayed",
    "sandbox_lifecycle_denied",
    "sandbox_process_changed",
    "sandbox_profile_not_enabled",
    "sandbox_result_changed",
    "skill_disabled",
    "tool_effect_unclassified",
    "tool_not_selected",
    "write_permission_denied",
    "write_tool_denied",
    "zdr_unavailable",
] as const;

export const DenyCodeV1Schema = z.enum(DENY_CODES_V1);
export type DenyCodeV1 = z.infer<typeof DenyCodeV1Schema>;

export const ERROR_CODES_V1 = [
    ...DENY_CODES_V1,
    "content_deleted",
    "external_outcome_unknown",
    "internal_error",
    "invalid_command",
    "invalid_cursor",
    "not_found",
    "rate_limited",
    "sandbox_protocol_error",
    "sandbox_cleanup_required",
    "sandbox_unavailable",
    "vendor_protocol_error",
] as const;

export const ErrorCodeV1Schema = z.enum(ERROR_CODES_V1);
export type ErrorCodeV1 = z.infer<typeof ErrorCodeV1Schema>;
