/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/sandbox-runner/wrangler.jsonc --env=preview --include-runtime=false apps/sandbox-runner/worker-configuration.d.ts` (hash: 8a532e377f7e25f01474e087781eb0f4)
interface __BaseEnv_Env {
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./entry");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
