/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/orchestrator/wrangler.d1.jsonc --env=preview --include-runtime=false apps/orchestrator/worker-configuration.d.ts` (hash: fe45fc1106a9d7c3f3012cb2539eda14)
interface __BaseEnv_Env {
	CONTROL_DB_FRESH: D1Database;
	RUN_OBJECT: DurableObjectNamespace /* RunObject from openbot-runtime-preview */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./entry.d1");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
