/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/orchestrator/wrangler.d1.jsonc --env=preview --include-runtime=false apps/orchestrator/worker-configuration.d.ts` (hash: edac9330f1e3af62226b447668196478)
interface __BaseEnv_Env {
	CONTROL_DB_FRESH: D1Database;
	RUN_OBJECT: DurableObjectNamespace /* RunObject from openbot-runtime-preview */;
	SANDBOX_LIFECYCLE: Service /* entrypoint SandboxLifecycleService from openbot-sandbox-runner-preview */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./entry.d1");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
