/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/runtime/wrangler.d1.jsonc --env=preview --include-runtime=false apps/runtime/worker-configuration.d.ts` (hash: c73e96c06e3d3a8520090db65c02ed69)
interface __BaseEnv_Env {
	RUN_OBJECT: DurableObjectNamespace<import("./src/entry.d1").RunObject>;
	CAPABILITY_GATEWAY: Fetcher /* openbot-capability-gateway-preview */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entry.d1");
		durableNamespaces: "RunObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
